enum ActionType {
    SESSION = 'SESSION',
    SET_AUTH_TOKEN = 'SET_AUTH_TOKEN',
    REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN',
    UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN',
    ADD_AUDITORS_ID = 'ADD_AUDITORS_ID',
    REMOVE_AUDITORS_ID = 'REMOVE_AUDITORS_ID',
    REMOVE_ALL_AUDITORS_ID = 'REMOVE_ALL_AUDITORS_ID'
}

export {ActionType}